services:
  - type: web
    name: blockchain-cert-backend
    env: node
    plan: free
    rootDir: certificate-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_TYPE
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: blockchain_db
          property: connectionString
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: BLOCKCHAIN_RPC_URL
        sync: false
      - key: BLOCKCHAIN_ADMIN_PRIVATE_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "https://blockchain-cert-shem-kipyegons-projects.vercel.app,http://localhost:8080"

databases:
  - name: blockchain_db
    plan: free
